spring.application.name=adoptions
#

#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
spring.ai.ollama.chat.model=gemma4:26b
#spring.ai.ollama.chat.model=gpt-oss:20b
spring.ai.ollama.embedding.model=embeddinggemma:latest
#
spring.ai.vectorstore.pgvector.initialize-schema=true
#
spring.ai.mcp.client.initialized=false
spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
#
spring.security.oauth2.client.registration.spring.provider=spring
spring.security.oauth2.client.registration.spring.client-id=spring
spring.security.oauth2.client.registration.spring.client-secret=spring
spring.security.oauth2.client.registration.spring.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spring.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.spring.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.spring.scope=openid,profile
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
